name: easy_moni
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^4.0.2
  # Routing
  go_router: ^17.2.3

  # Networking
  dio: ^5.9.1

  # Logging
  talker: ^5.1.13
  talker_flutter: ^5.1.13
  talker_dio_logger: ^5.1.13
  talker_riverpod_logger: ^5.1.13

  # UI Components
  pull_to_refresh: ^2.0.0


  # Utils
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^4.0.4-dev.1
  freezed: ^3.2.6-dev.1
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.9.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_gen:
  output: lib/gen/
#  integrations:
#    flutter_svg: true